return {
  -- "nvimtools/none-ls.nvim",
  -- dependencies = {
  --   "gwinn/none-ls-jsonlint.nvim",
  -- },
  -- config = function()
  --   local null_ls = require("null-ls")
  --   null_ls.setup({
  --     sources = {
  --       -- YAML + JSON
  --       null_ls.builtins.formatting.prettier,
  --       null_ls.builtins.diagnostics.yamllint,
  --       require("none-ls-jsonlint.diagnostics.jsonlint"),
  --       -- Terraform
  --       null_ls.builtins.formatting.terraform_fmt,
  --       null_ls.builtins.diagnostics.terraform_validate,
  --       -- Python
  --       null_ls.builtins.formatting.black,
  --       null_ls.builtins.diagnostics.pylint,
  --     },
  --     --on_attach = function(client, bufnr)
  --     --  if vim.api.nvim_buf_get_name(bufnr) == "" then
  --     --    vim.bo[bufnr].buftype = ""
  --     --  end
  --     --end,
  --   })
  --
  --   vim.api.nvim_create_user_command("Format", function()
  --     vim.lsp.buf.format({})
  --   end, {})
  --   vim.keymap.set({ "n" }, "<leader>cf", ":Format<CR>", { desc = "Format" })
  -- end,
}
